### ISSUE TITLE
Update responsive styles to use CSS grid

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/trevordmiller-website#242]
```css
.app {
  display: grid;
  grid-column-gap: 15px;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
}
```

👋 bye to media queries and hacky flexbox :)
